### PR TITLE
navbar admin mode

### LINKED ISSUE #29: Navbar + Page Routing
image

Implement this navbar, and the page routing

### PR DESCRIPTION
**Pull request by pratyush1718**
## Tracking Info

Resolves #29

## Changes

Added horizontal and vertical nav bar for admin node

## Testing

tested on http://localhost:3000/

## Confirmation of Change

image

### CODE REVIEW

**Review by Anthonyp0329 — CHANGES_REQUESTED** [review]
Great work Pratyush! Just some styling issues with the top navbar, the sideline sidekick text shouldn't be stacking, and the search bar isn't centered, also the profile icon isn't showing. Also, if you could put the components and their styles into a dedicated components folder. I think these issues just occur on smaller screens.Thanks! 
image

**Comment by meganleongg** [comment]
Great work!! On top of the styling issues with the top navbar, I noticed the logos along the side bar are misaligned, "Home" seems to be a lighter weight boldness than "Search" and "General Principles", and the spacing between categories under General Principles seems stacked tighter together than the Figma designs intended.

**Review by LillianHo5 — COMMENTED** [review]
This looks great! Aside from what was mentioned in the above comments, I noticed that the chevron/arrow should be pointing right when inactive instead of pointing down from the Figma. It also seems that the "All" should be bolded.
Screenshot 2024-04-22 at 6 28 25 PM

**Comment by pratyush1718** [comment]
All the above comments have been addressed. @Anthonyp0329 and I have decided to push without the arrow direction change for now.

**Review by Anthonyp0329 — APPROVED** [review]

**Pull request merged**
