### PR TITLE
General principles page

### LINKED ISSUE #5: General Principles Page
Implement general principles page as shown in the Figma, can hardcode text for now. 

image

### PR DESCRIPTION
**Pull request by PiXlRAM**
## Tracking Info

Resolves #5 

## Changes

Created General Principles and Emergency Care pages, created bullet point component that is used in a lot of other pages with the same format at General Principles (such as Emergency Care), used nested list view for multiple subpoints

## Testing

Checked the page on iOS device and Android virtual device, both of which were different screen sizes too, worked fine in all cases.

## Confirmation of Change

image

### CODE REVIEW

**Review by Anthonyp0329 — CHANGES_REQUESTED** [review]
Looks awesome, great work guys, especially with making the bullet point component. Just a few changes before this is ready to merge - make sure to put the styles into a separate file for each component, so BulletPointStyles, generalPrinciplesStyles, etc. Also, remove any changes to App.tsx for now. Then, should be good to go! Thanks!

**Review by LillianHo5 — APPROVED** [review]
This looks good to me! Aside from what Anthony mentioned, one thing I noticed was this error message showing up when running the IOS/Android emulators: 

ERROR  fontFamily "Roboto" is not a system font and has not been loaded through Font.loadAsync.
- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
- If this is a custom font, be sure to load it with Font.loadAsync. 

I also had this error with my task, and I thought that this thread and docs were helpful: https://stackoverflow.com/questions/57066075/console-error-fontfamily-roboto-medium-is-not-a-system-font-and-has-not-been, https://docs.expo.dev/develop/user-interface/fonts/#using-fontloadasync-instead-of-the-usefonts-hook.

**Comment by eshaan-s18** [comment]
Looks awesome guys! Great job, especially with those bullet point components. Aside from what Anthony and Lillian mentioned, it appears to run well for me. Approving this PR, great job guys!

**Review by eshaan-s18 — APPROVED** [review]
Looks awesome guys! Great job, especially with those bullet point components. Aside from what Anthony and Lillian mentioned, it appears to run well for me. Approving this PR, great job guys!

**Review by Anthonyp0329 — APPROVED** [review]
Thanks for fixing the linting issues, is good to merge!

**Pull request merged**
